# Project information
site_name: Agent Development Kit
site_url: https://google.github.io/adk-docs
site_description: >-
  Build powerful multi-agent systems with Agent Development Kit
site_dir: site
exclude_docs:
  api-reference/java/legal/*

# Repository
repo_name: adk-docs
repo_url: https://github.com/google/adk-docs
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright Google 2025&nbsp;&nbsp;|&nbsp;&nbsp;<a href="//policies.google.com/terms">Terms</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="//policies.google.com/privacy">Privacy</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="#__consent">Manage cookies</a>

# Custom CSS
extra_css:
  - stylesheets/custom.css
  - stylesheets/language-tags.css

extra:
  first_repo_url: https://github.com/google/adk-python
  first_repo_name: adk-python
  first_repo_icon: fontawesome/brands/github
  second_repo_url: https://github.com/google/adk-go
  second_repo_name: adk-go
  second_repo_icon: fontawesome/brands/github
  third_repo_url: https://github.com/google/adk-java
  third_repo_name: adk-java
  third_repo_icon: fontawesome/brands/github
  analytics:
    provider: google
    property: G-DKHZS27PHP
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize repeated visits and preferences,
      as well as to measure the effectiveness of our documentation and
      whether users find the information they need. With your consent,
      you're helping us to make our documentation better.

# Configuration
theme:
  name: material
  font:
    text: Google Sans
    code: Roboto Mono
  logo: assets/agent-development-kit.png
  favicon: assets/agent-development-kit.png
  icon:
    repo: fontawesome/brands/github
  custom_dir: overrides
  palette:
    - scheme: default
      primary: white
      accent: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: white
      accent: white
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - toc.follow

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      dedent_subsections: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - toc:
      permalink: true


# Plugins
plugins:
  - search
  - redirects:
      redirect_maps:
        'get-started/local-testing.md': 'runtime/api-server.md'
        'get-started/tutorial.md': 'tutorials/index.md'
        'guides/responsible-agents.md': 'safety/index.md'
        'tools/third-party-tools.md': 'tools/third-party/index.md'
        'tools/third-party/openapi-tools.md': 'tools-custom/openapi-tools.md'
        'tools/openapi-tools.md': 'tools-custom/openapi-tools.md'
        'tutorials/ag-ui.md': 'tools/third-party/ag-ui.md'
        'tools/third-party/langchain.md': 'tools/index.md'
        'tools/third-party/crewai.md': 'tools/index.md'
        'get-started/testing.md': 'runtime/api-server.md'

# Navigation
nav:
  - Home:
    - index.md
  - Build Agents:
    - Get Started:
      - get-started/index.md
      - Python: get-started/python.md
      - Go: get-started/go.md
      - Java: get-started/java.md
    - Build your Agent:
      - tutorials/index.md
      - Multi-tool agent: get-started/quickstart.md
      - Agent team: tutorials/agent-team.md
      - Streaming agent:
        - get-started/streaming/index.md
        - Python: get-started/streaming/quickstart-streaming.md
        - Java: get-started/streaming/quickstart-streaming-java.md
      - Advanced setup: get-started/installation.md
    - Agents:
      - agents/index.md
      - LLM agents: agents/llm-agents.md
      - Workflow agents:
        - agents/workflow-agents/index.md
        - Sequential agents: agents/workflow-agents/sequential-agents.md
        - Loop agents: agents/workflow-agents/loop-agents.md
        - Parallel agents: agents/workflow-agents/parallel-agents.md
      - Custom agents: agents/custom-agents.md
      - Multi-agent systems: agents/multi-agents.md
      - Agent Config: agents/config.md
      - Models & Authentication: agents/models.md
    - Tools for Agents:
      - tools/index.md
      - Built-in tools: tools/built-in-tools.md
      - Gemini API tools:
        -  Computer use: tools/gemini-api/computer-use.md
      - Google Cloud tools:
        - Overview: tools/google-cloud-tools.md
        - MCP Toolbox for Databases: tools/google-cloud/mcp-toolbox-for-databases.md
        - Code Execution with Agent Engine: tools/google-cloud/code-exec-agent-engine.md
      - Third-party tools:
        - tools/third-party/index.md
        - Browserbase: tools/third-party/browserbase.md
        - Exa: tools/third-party/exa.md
        - Firecrawl: tools/third-party/firecrawl.md
        - GitHub: tools/third-party/github.md
        - Hugging Face: tools/third-party/hugging-face.md
        - Notion: tools/third-party/notion.md
        - Tavily: tools/third-party/tavily.md
        - Agentic UI (AG-UI): tools/third-party/ag-ui.md
    - Custom Tools:
      - tools-custom/index.md
      - Function tools:
        - Overview: tools/function-tools.md
        - Tool performance: tools/performance.md
        - Action confirmations: tools/confirmation.md
      - MCP tools: tools/mcp-tools.md
      - OpenAPI tools: tools-custom/openapi-tools.md
      - Authentication: tools/authentication.md
  - Run Agents:
    - Agent Runtime:
      - Agent Runtime: runtime/index.md
      - Runtime Config: runtime/runconfig.md
      - API Server: runtime/api-server.md
      - Resume Agents: runtime/resume.md
    - Deployment:
      - deploy/index.md
      - Agent Engine: deploy/agent-engine.md
      - Cloud Run: deploy/cloud-run.md
      - GKE: deploy/gke.md
    - Observability:
      - Logging: observability/logging.md
      - Cloud Trace: observability/cloud-trace.md
      - AgentOps: observability/agentops.md
      - Arize AX: observability/arize-ax.md
      - Datadog: observability/datadog.md
      - Freeplay: observability/freeplay.md
      - Phoenix: observability/phoenix.md
      - W&B Weave: observability/weave.md
    - Evaluation:
      - evaluate/index.md
      - Criteria: evaluate/criteria.md
      - User Simulation: evaluate/user-sim.md
    - Safety and Security:
      - safety/index.md
  - Components:
    - Technical Overview: get-started/about.md
    - Context:
      - context/index.md
      - Context caching: context/caching.md
      - Context compression: context/compaction.md
    - Sessions & Memory:
      - sessions/index.md
      - Session: sessions/session.md
      - State: sessions/state.md
      - Memory: sessions/memory.md
      - Vertex AI Express Mode: sessions/express-mode.md
    - Callbacks:
      - callbacks/index.md
      - Types of callbacks: callbacks/types-of-callbacks.md
      - Callback patterns: callbacks/design-patterns-and-best-practices.md
    - Artifacts:
      - artifacts/index.md
    - Events:
      - events/index.md
    - Plugins:
      - plugins/index.md
      - Reflect and retry: plugins/reflect-and-retry.md
    - MCP:
      - mcp/index.md
    - A2A Protocol:
      - a2a/index.md
      - Introduction to A2A: a2a/intro.md
      - A2A Quickstart (Exposing): a2a/quickstart-exposing.md
      - A2A Quickstart (Exposing) (Go): a2a/quickstart-exposing-go.md
      - A2A Quickstart (Consuming): a2a/quickstart-consuming.md
      - A2A Quickstart (Consuming) (Go): a2a/quickstart-consuming-go.md
    - Bidi-streaming (live):
      - streaming/index.md
      - Custom Audio Bidi-streaming app sample (WebSockets): streaming/custom-streaming-ws.md
      - Bidi-streaming development guide series: streaming/dev-guide/part1.md
      - Streaming Tools: streaming/streaming-tools.md
      - Configurating Bidi-streaming behaviour: streaming/configuration.md
    - Grounding:
      - Understanding Google Search Grounding: grounding/google_search_grounding.md
      - Understanding Vertex AI Search Grounding: grounding/vertex_ai_search_grounding.md
  - Reference:
    - API Reference:
      - api-reference/index.md
      - Python ADK: api-reference/python/index.html
      - Go ADK: https://pkg.go.dev/google.golang.org/adk" target="_blank
      - Java ADK: api-reference/java/index.html
      - CLI Reference: api-reference/cli/index.html
      - Agent Config reference: api-reference/agentconfig/index.html
      - REST API: api-reference/rest/index.md
    - Community Resources: community.md
    - Contributing Guide: contributing-guide.md
